# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from wos-journals-client-py.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from wos-journals-client-py.model.inline_response200 import InlineResponse200
from wos-journals-client-py.model.inline_response2001 import InlineResponse2001
from wos-journals-client-py.model.inline_response2001_categories import InlineResponse2001Categories
from wos-journals-client-py.model.inline_response2001_journal_citation_reports import InlineResponse2001JournalCitationReports
from wos-journals-client-py.model.inline_response2001_open_access import InlineResponse2001OpenAccess
from wos-journals-client-py.model.inline_response2001_publisher import InlineResponse2001Publisher
from wos-journals-client-py.model.inline_response2002 import InlineResponse2002
from wos-journals-client-py.model.inline_response2002_journal import InlineResponse2002Journal
from wos-journals-client-py.model.inline_response2002_journal_data import InlineResponse2002JournalData
from wos-journals-client-py.model.inline_response2002_journal_data_cited import InlineResponse2002JournalDataCited
from wos-journals-client-py.model.inline_response2002_journal_data_citing import InlineResponse2002JournalDataCiting
from wos-journals-client-py.model.inline_response2002_journal_profile import InlineResponse2002JournalProfile
from wos-journals-client-py.model.inline_response2002_journal_profile_citable_items import InlineResponse2002JournalProfileCitableItems
from wos-journals-client-py.model.inline_response2002_journal_profile_citations import InlineResponse2002JournalProfileCitations
from wos-journals-client-py.model.inline_response2002_journal_profile_occurrence_countries import InlineResponse2002JournalProfileOccurrenceCountries
from wos-journals-client-py.model.inline_response2002_journal_profile_occurrence_organizations import InlineResponse2002JournalProfileOccurrenceOrganizations
from wos-journals-client-py.model.inline_response2002_metrics import InlineResponse2002Metrics
from wos-journals-client-py.model.inline_response2002_metrics_impact_metrics import InlineResponse2002MetricsImpactMetrics
from wos-journals-client-py.model.inline_response2002_metrics_influence_metrics import InlineResponse2002MetricsInfluenceMetrics
from wos-journals-client-py.model.inline_response2002_metrics_influence_metrics_eigen_factor import InlineResponse2002MetricsInfluenceMetricsEigenFactor
from wos-journals-client-py.model.inline_response2002_metrics_source_metrics import InlineResponse2002MetricsSourceMetrics
from wos-journals-client-py.model.inline_response2002_metrics_source_metrics_citable_items import InlineResponse2002MetricsSourceMetricsCitableItems
from wos-journals-client-py.model.inline_response2002_metrics_source_metrics_half_life import InlineResponse2002MetricsSourceMetricsHalfLife
from wos-journals-client-py.model.inline_response2002_ranks import InlineResponse2002Ranks
from wos-journals-client-py.model.inline_response2002_ranks_esi_citations import InlineResponse2002RanksEsiCitations
from wos-journals-client-py.model.inline_response2002_ranks_jif import InlineResponse2002RanksJif
from wos-journals-client-py.model.inline_response2002_source_data import InlineResponse2002SourceData
from wos-journals-client-py.model.inline_response2002_source_data_articles import InlineResponse2002SourceDataArticles
from wos-journals-client-py.model.inline_response2003 import InlineResponse2003
from wos-journals-client-py.model.inline_response2003_citing import InlineResponse2003Citing
from wos-journals-client-py.model.inline_response2003_hits import InlineResponse2003Hits
from wos-journals-client-py.model.inline_response2003_journal import InlineResponse2003Journal
from wos-journals-client-py.model.inline_response2004 import InlineResponse2004
from wos-journals-client-py.model.inline_response2004_hits import InlineResponse2004Hits
from wos-journals-client-py.model.inline_response2005 import InlineResponse2005
from wos-journals-client-py.model.inline_response2005_category_citation_reports import InlineResponse2005CategoryCitationReports
from wos-journals-client-py.model.inline_response2005_hits import InlineResponse2005Hits
from wos-journals-client-py.model.inline_response2006 import InlineResponse2006
from wos-journals-client-py.model.inline_response2007 import InlineResponse2007
from wos-journals-client-py.model.inline_response2007_category_data import InlineResponse2007CategoryData
from wos-journals-client-py.model.inline_response2007_category_data_cited import InlineResponse2007CategoryDataCited
from wos-journals-client-py.model.inline_response2007_frequency import InlineResponse2007Frequency
from wos-journals-client-py.model.inline_response2007_immediacy import InlineResponse2007Immediacy
from wos-journals-client-py.model.inline_response2007_jif import InlineResponse2007Jif
from wos-journals-client-py.model.inline_response2007_jif_aggregate import InlineResponse2007JifAggregate
from wos-journals-client-py.model.inline_response2007_journals import InlineResponse2007Journals
from wos-journals-client-py.model.inline_response2007_source_data import InlineResponse2007SourceData
from wos-journals-client-py.model.inline_response2007_source_data_articles import InlineResponse2007SourceDataArticles
from wos-journals-client-py.model.inline_response2007_source_data_reviews import InlineResponse2007SourceDataReviews
from wos-journals-client-py.model.inline_response2008 import InlineResponse2008
from wos-journals-client-py.model.inline_response2008_hits import InlineResponse2008Hits
from wos-journals-client-py.model.inline_response2008_journal import InlineResponse2008Journal
from wos-journals-client-py.model.inline_response2009 import InlineResponse2009
from wos-journals-client-py.model.inline_response2009_hits import InlineResponse2009Hits
from wos-journals-client-py.model.inline_response2009_journal import InlineResponse2009Journal
from wos-journals-client-py.model.inline_response200_categories import InlineResponse200Categories
from wos-journals-client-py.model.inline_response200_hits import InlineResponse200Hits
from wos-journals-client-py.model.inline_response200_journal_citation_reports import InlineResponse200JournalCitationReports
from wos-journals-client-py.model.inline_response200_metrics import InlineResponse200Metrics
from wos-journals-client-py.model.inline_response200_metrics_impact_metrics import InlineResponse200MetricsImpactMetrics
from wos-journals-client-py.model.inline_response200_metrics_source_metrics import InlineResponse200MetricsSourceMetrics
from wos-journals-client-py.model.inline_response200_ranks import InlineResponse200Ranks
from wos-journals-client-py.model.inline_response200_ranks_jif import InlineResponse200RanksJif
from wos-journals-client-py.model.metadata import Metadata
from wos-journals-client-py.model.search_match import SearchMatch
